### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [elizabethmcd/metabolisHMM#46]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2.22. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary metabolishmm -w /tmp/ext metabolishmm==2.22
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting metabolishmm==2.22
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ea0/9df216c0fb79a/metabolisHMM-2.22.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-wkurcu8f/metabolishmm/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-wkurcu8f/metabolishmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-wkurcu8f/metabolishmm/pip-egg-info
         cwd: /tmp/pip-wheel-wkurcu8f/metabolishmm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-wkurcu8f/metabolishmm/setup.py", line 4, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by elizabethmcd** [comment]
Sorry, I think I'm confused about what files were missing, and what files you added in the pull request to fix the above issue.

**Comment by thatch** [comment]
The sdist command only includes a few files automatically; for anything like requirements.txt you want, you have to specify it in `MANIFEST.in`

See https://docs.python.org/3/distutils/sourcedist.html

**Comment by elizabethmcd** [comment]
reconfigured in 2.3.0 to not include requirements.txt in dev branch
